name: generate animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: tpgusgh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push to githubsnake repo
        run: |
          rm -rf dist/.git
          cd dist
          git init
          git config user.name "tpgusgh"
          git config user.email "kimhyunhi1@gmail.com"
          git add .
          git commit -m "update snake animation"
          git push --force https://${{ secrets.PAT_TOKEN }}@github.com/tpgusgh/githubsnake.git main